substitutions:
  _SERVICE_NAME: hello-world-dev
  _ENVIRONMENT: dev
  _REGION: europe-west1

steps:
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE_NAME}
      - --source
      - .
      - --region
      - ${_REGION}
      - --allow-unauthenticated
      - --set-env-vars
      - ENVIRONMENT=${_ENVIRONMENT},DATABASE_BUCKET=${PROJECT_ID}-hello-world-data

options:
  logging: CLOUD_LOGGING_ONLY
