"""
Zone hierarchy seed data: L1 zones, L2 sub-zones, L3 SaaS capabilities.
Each zone has a 90s pop-star zone owner.
"""

ZONES = [
    {
        "id": "z1",
        "name": "Customer & Revenue",
        "owner_name": "Britney Spears",
        "owner_image": "/static/zones/zone-z1.jpg",
        "description": "Growth, monetisation, and customer lifecycle for the SaaS product.",
        "sub_zones": [
            {
                "name": "Growth & Acquisition",
                "capabilities": [
                    "Inbound Marketing Automation",
                    "Product-Led Growth Funnel",
                    "Partner Referral Management",
                    "Trial Conversion Orchestration",
                    "SEO & Content Publishing",
                    "Paid Campaign Attribution",
                    "Landing Page Optimisation",
                ],
            },
            {
                "name": "Billing & Monetisation",
                "capabilities": [
                    "Subscription Lifecycle Management",
                    "Usage Metering & Rating",
                    "Invoice & Payment Processing",
                    "Pricing & Packaging Engine",
                    "Revenue Recognition",
                    "Dunning & Collections",
                    "Tax & Compliance Calculation",
                    "Proration & Credits",
                ],
            },
            {
                "name": "Customer Success",
                "capabilities": [
                    "Customer Health Scoring",
                    "Onboarding Journey Orchestration",
                    "Support Ticket Routing",
                    "Knowledge Base & Self-Service",
                    "NPS & Feedback Collection",
                    "Renewal Risk Prediction",
                    "Success Plan Management",
                ],
            },
            {
                "name": "Sales Operations",
                "capabilities": [
                    "CRM Synchronisation",
                    "Lead Routing & Assignment",
                    "Quote-to-Cash Workflow",
                    "Territory Management",
                    "Pipeline Analytics",
                    "Sales Forecasting",
                    "Proposal Automation",
                    "Deal Desk Approvals",
                ],
            },
            {
                "name": "Partner Ecosystem",
                "capabilities": [
                    "Partner Onboarding Portal",
                    "Co-selling Workspace",
                    "Marketplace Integration",
                    "Channel Performance Analytics",
                    "Deal Registration",
                    "Commission Calculation",
                    "Partner Certification Tracking",
                ],
            },
            {
                "name": "Customer Identity",
                "capabilities": [
                    "SSO & Federation",
                    "Customer Profile Management",
                    "Consent & Preference Centre",
                    "Account Linking",
                    "Guest Access Management",
                    "Directory Synchronisation",
                ],
            },
        ],
    },
    {
        "id": "z2",
        "name": "Product Engineering",
        "owner_name": "Mel B (Spice Girls)",
        "owner_image": "/static/zones/zone-z2.jpg",
        "description": "Application delivery, developer experience, and product quality.",
        "sub_zones": [
            {
                "name": "Core Application Platform",
                "capabilities": [
                    "Multi-tenant Runtime",
                    "Feature Flag Service",
                    "Release Management",
                    "Public API Gateway",
                    "Service Mesh",
                    "Central Configuration",
                    "Error Tracking & Alerting",
                    "Rate Limiting & Quotas",
                ],
            },
            {
                "name": "Mobile Experience",
                "capabilities": [
                    "iOS Client Application",
                    "Android Client Application",
                    "Push Notification Service",
                    "Offline Sync Engine",
                    "Mobile App Store Pipeline",
                    "Device Management",
                    "Mobile Analytics",
                ],
            },
            {
                "name": "Web Experience",
                "capabilities": [
                    "Single Page Application Shell",
                    "Design System & Components",
                    "Server-side Rendering Platform",
                    "CDN & Edge Delivery",
                    "A/B Testing Framework",
                    "Accessibility Compliance",
                    "Web Performance Monitoring",
                    "Internationalisation",
                ],
            },
            {
                "name": "Developer Platform",
                "capabilities": [
                    "Internal SDK Library",
                    "API Documentation Portal",
                    "Sandbox Environments",
                    "Developer CLI Tooling",
                    "Code Scaffolding Templates",
                    "Webhook Dispatcher",
                    "Developer Sandbox Billing",
                ],
            },
            {
                "name": "Quality Engineering",
                "capabilities": [
                    "Test Automation Framework",
                    "Load & Performance Testing",
                    "Chaos Engineering",
                    "Visual Regression Testing",
                    "Security Scanning in CI",
                    "Test Data Management",
                    "Continuous Integration Pipelines",
                ],
            },
            {
                "name": "Product Analytics",
                "capabilities": [
                    "Product Event Ingestion",
                    "Funnel Analysis",
                    "Cohort Reporting",
                    "Experimentation Platform",
                    "Session Replay",
                    "Feature Adoption Metrics",
                    "Product KPI Dashboards",
                ],
            },
        ],
    },
    {
        "id": "z3",
        "name": "Platform & Cloud",
        "owner_name": "Nick Carter (Backstreet Boys)",
        "owner_image": "/static/zones/zone-z3.jpg",
        "description": "Cloud infrastructure, integration fabric, and operational resilience.",
        "sub_zones": [
            {
                "name": "Compute & Orchestration",
                "capabilities": [
                    "Kubernetes Cluster Management",
                    "Container Registry",
                    "Serverless Runtime",
                    "Batch Job Scheduler",
                    "Autoscaling Policies",
                    "Workload Isolation",
                    "GPU Workload Pools",
                ],
            },
            {
                "name": "Networking",
                "capabilities": [
                    "VPC & Subnet Design",
                    "Load Balancing",
                    "DNS Management",
                    "CDN Integration",
                    "Private Service Connect",
                    "Firewall Rule Management",
                    "Traffic Routing Policies",
                    "Zero Trust Network Access",
                ],
            },
            {
                "name": "Observability",
                "capabilities": [
                    "Metrics Collection",
                    "Log Aggregation",
                    "Distributed Tracing",
                    "Alerting & Escalation",
                    "SLO Dashboards",
                    "Incident Timeline",
                    "Synthetic Monitoring",
                ],
            },
            {
                "name": "Integration Platform",
                "capabilities": [
                    "Message Queue Service",
                    "Enterprise Event Bus",
                    "ETL Pipeline Orchestration",
                    "iPaaS Connectors",
                    "Schema Registry",
                    "API Management",
                    "Webhook Ingress Gateway",
                    "File Transfer Hub",
                ],
            },
            {
                "name": "Environment Management",
                "capabilities": [
                    "Infrastructure as Code",
                    "Environment Provisioning",
                    "Secrets Management",
                    "Configuration Drift Detection",
                    "Cloud Cost Allocation",
                    "Resource Tagging Standards",
                    "Operational Runbooks",
                ],
            },
            {
                "name": "Disaster Recovery",
                "capabilities": [
                    "Backup Automation",
                    "Cross-region Replication",
                    "Failover Orchestration",
                    "RPO/RTO Monitoring",
                    "Recovery Testing",
                    "Archive Storage",
                    "Business Continuity Planning",
                ],
            },
        ],
    },
    {
        "id": "z4",
        "name": "Data & Intelligence",
        "owner_name": "Mariah Carey",
        "owner_image": "/static/zones/zone-z4.jpg",
        "description": "Data platforms, analytics, and machine learning capabilities.",
        "sub_zones": [
            {
                "name": "Data Ingestion",
                "capabilities": [
                    "Real-time Stream Ingestion",
                    "Batch Data Imports",
                    "Change Data Capture",
                    "File Landing Zone",
                    "API Data Feeds",
                    "Schema Validation",
                    "Data Quality Checks",
                ],
            },
            {
                "name": "Data Warehouse",
                "capabilities": [
                    "Dimensional Modelling",
                    "ELT Orchestration",
                    "Departmental Data Marts",
                    "Semantic Layer",
                    "Query Optimisation",
                    "Partition Management",
                    "Warehouse Cost Governance",
                    "Slowly Changing Dimensions",
                ],
            },
            {
                "name": "Business Intelligence",
                "capabilities": [
                    "Executive Dashboards",
                    "Self-service BI",
                    "Embedded Analytics",
                    "KPI Catalog",
                    "Scheduled Reporting",
                    "Data Storytelling",
                    "Metric Lineage",
                ],
            },
            {
                "name": "Machine Learning",
                "capabilities": [
                    "Feature Store",
                    "Model Training Pipelines",
                    "Model Serving Infrastructure",
                    "MLOps Automation",
                    "Experiment Tracking",
                    "Model Monitoring",
                    "Responsible AI Controls",
                    "LLM Gateway",
                ],
            },
            {
                "name": "Master Data Management",
                "capabilities": [
                    "Customer MDM",
                    "Product Catalog",
                    "Reference Data Hub",
                    "Data Stewardship Workflow",
                    "Golden Record Management",
                    "Hierarchy Management",
                    "Data Contracts",
                ],
            },
            {
                "name": "Privacy & Governance",
                "capabilities": [
                    "Enterprise Data Catalog",
                    "Access Policy Engine",
                    "Retention Rule Management",
                    "PII Masking",
                    "Data Lineage Tracking",
                    "Compliance Reporting",
                    "Audit Trail Storage",
                ],
            },
            {
                "name": "Real-time Analytics",
                "capabilities": [
                    "Stream Processing Engine",
                    "Operational Dashboards",
                    "Anomaly Detection",
                    "Real-time Segmentation",
                    "Event Correlation",
                    "Alert Rule Engine",
                ],
            },
        ],
    },
    {
        "id": "z5",
        "name": "Security & Compliance",
        "owner_name": "Janet Jackson",
        "owner_image": "/static/zones/zone-z5.jpg",
        "description": "Identity, application security, and regulatory compliance.",
        "sub_zones": [
            {
                "name": "Identity & Access",
                "capabilities": [
                    "IAM Policy Management",
                    "Multi-factor Authentication",
                    "Role-based Access Control",
                    "Privileged Access Management",
                    "Enterprise SSO Integration",
                    "Session Management",
                    "Periodic Access Reviews",
                    "Just-in-time Access",
                ],
            },
            {
                "name": "Application Security",
                "capabilities": [
                    "Static Application Security Testing",
                    "Dynamic Application Security Testing",
                    "Dependency Vulnerability Scanning",
                    "Penetration Testing Programme",
                    "Secure SDLC Controls",
                    "Threat Modelling",
                    "Bug Bounty Platform",
                ],
            },
            {
                "name": "Infrastructure Security",
                "capabilities": [
                    "Network Segmentation",
                    "Web Application Firewall",
                    "DDoS Protection",
                    "Certificate Lifecycle Management",
                    "Hardening Baselines",
                    "Vulnerability Management",
                    "SIEM Integration",
                ],
            },
            {
                "name": "Compliance Operations",
                "capabilities": [
                    "SOC 2 Control Library",
                    "GDPR Operations",
                    "PCI Scope Management",
                    "Audit Evidence Collection",
                    "Policy Management",
                    "Control Testing Automation",
                    "Vendor Risk Assessment",
                    "Regulatory Change Tracking",
                ],
            },
            {
                "name": "Data Protection",
                "capabilities": [
                    "Encryption at Rest",
                    "Encryption in Transit",
                    "Key Management Service",
                    "Tokenisation Service",
                    "Data Loss Prevention",
                    "Secrets Rotation",
                    "Backup Encryption",
                ],
            },
            {
                "name": "Incident Response",
                "capabilities": [
                    "Incident Response Playbooks",
                    "Digital Forensics Toolkit",
                    "Breach Notification Workflow",
                    "Tabletop Exercise Programme",
                    "Security Operations Centre",
                    "Threat Intelligence Feeds",
                    "Recovery Coordination",
                ],
            },
        ],
    },
    {
        "id": "z6",
        "name": "Business Operations",
        "owner_name": "Ricky Martin",
        "owner_image": "/static/zones/zone-z6.jpg",
        "description": "Corporate systems supporting finance, HR, legal, and workplace IT.",
        "sub_zones": [
            {
                "name": "Finance Systems",
                "capabilities": [
                    "General Ledger",
                    "Accounts Payable",
                    "Accounts Receivable",
                    "Procurement",
                    "Expense Management",
                    "Budget Planning",
                    "Financial Close Automation",
                    "Intercompany Accounting",
                ],
            },
            {
                "name": "Human Resources",
                "capabilities": [
                    "HR Information System",
                    "Payroll Processing",
                    "Benefits Administration",
                    "Talent Acquisition Platform",
                    "Performance Management",
                    "Learning Management System",
                    "Workforce Planning",
                ],
            },
            {
                "name": "Legal & Contracts",
                "capabilities": [
                    "Contract Lifecycle Management",
                    "Electronic Signature",
                    "Intellectual Property Register",
                    "Regulatory Filing Tracker",
                    "Contract Analytics",
                    "Obligation Tracking",
                    "Legal Request Intake",
                ],
            },
            {
                "name": "Workplace IT",
                "capabilities": [
                    "Endpoint Management",
                    "Collaboration Suite",
                    "IT Service Desk",
                    "Asset Inventory",
                    "Software Licence Management",
                    "Patch Management",
                    "Virtual Desktop Infrastructure",
                ],
            },
            {
                "name": "Vendor Management",
                "capabilities": [
                    "Vendor Onboarding",
                    "SLA Tracking",
                    "Invoice Matching",
                    "Vendor Performance Scorecards",
                    "Contract Renewal Alerts",
                    "Spend Analytics",
                    "Third-party Risk Monitoring",
                ],
            },
            {
                "name": "Corporate Planning",
                "capabilities": [
                    "OKR Tracking",
                    "Portfolio Planning",
                    "Capacity Planning",
                    "Strategic Roadmaps",
                    "Executive Reporting",
                    "Initiative Tracking",
                    "Benefits Realisation",
                ],
            },
        ],
    },
]

# Entity → sub-zone name mappings used during seeding.
PROJECT_SUB_ZONES = {
    "p1": "Web Experience",
    "p2": "Mobile Experience",
    "p3": "Finance Systems",
}

RISK_SUB_ZONES = {
    "r1": "Growth & Acquisition",
    "r2": "Customer Success",
    "r3": "Core Application Platform",
    "r4": "Finance Systems",
}

ARCHITECTURE_ASSIGNMENTS = {
    "a1": ("Web Experience", "Single Page Application Shell"),
    "a2": ("Mobile Experience", "iOS Client Application"),
    "a3": ("Integration Platform", "API Management"),
    "a4": ("Finance Systems", "General Ledger"),
    "a5": ("Data Warehouse", "ELT Orchestration"),
    "a6": ("Customer Success", "Support Ticket Routing"),
    "a7": ("Integration Platform", "File Transfer Hub"),
    "a8": ("Integration Platform", "Enterprise Event Bus"),
    "a9": ("Data Warehouse", "Departmental Data Marts"),
    "a10": ("Identity & Access", "Enterprise SSO Integration"),
}
